version: "3"

services:

  # Postgres database
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres  # Replace with your password
      POSTGRES_USER: postgres  # Replace with your username
      POSTGRES_DB: chat-app-db  # Replace with your database name
    volumes:
      - ./postgres_data:/var/lib/postgresql/data  # Persist database data
    ports:
      - "5432:5432"  # Expose Postgres port
